[theme]
# A cor principal (Botões primários, gráficos, destaques)
primaryColor = "#007BFF"

# A cor de fundo da página (Um modo escuro elegante, não 100% preto para não cansar a vista)
backgroundColor = "#0E1117"

# A cor de fundo secundária (Barra lateral, caixas de métricas, st.form)
secondaryBackgroundColor = "#262730"

# A cor do texto
textColor = "#FAFAFA"

# A fonte do sistema (sans serif fica mais limpo e moderno)
font = "sans serif"